//! 權重定義 / Autogenerated-style weight definitions for `pallet-interop`.
//!
//! 目前為佔位數值；正式權重應由 `frame-benchmarking` 產生並取代本檔。
//!
//! Placeholder weights. Production weights should be generated via
//! `frame-benchmarking` and substituted here (see `benchmarking.rs`).
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// 本 pallet 交易所需的權重資訊介面。
///
/// Weight functions needed for `pallet_interop`.
pub trait WeightInfo {
    fn register_issuer() -> Weight;
    fn submit_instruction() -> Weight;
    fn verify_finality() -> Weight;
    fn net_and_settle() -> Weight;
    fn register_validator() -> Weight;
    fn slash_validator() -> Weight;
    fn init_authority_set() -> Weight;
    fn rotate_authority_set() -> Weight;
    fn register_issuer_vk() -> Weight;
    fn verify_foreign_proof() -> Weight;
    fn register_treaty() -> Weight;
    fn recognize_foreign_invoice() -> Weight;
    fn oss_register() -> Weight;
    fn oss_report() -> Weight;
}

/// 以實機基準測試產生的權重（佔位）。
///
/// Weights for `pallet_interop` using the Substrate node and recommended
/// hardware (placeholder values).
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn register_issuer() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn submit_instruction() -> Weight {
        Weight::from_parts(18_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn verify_finality() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn net_and_settle() -> Weight {
        // 多邊淨額清算需走訪所有指令；以保守上限作為佔位。
        // Multilateral netting iterates over all instructions; a conservative
        // upper bound is used as a placeholder.
        Weight::from_parts(50_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(64))
            .saturating_add(T::DbWeight::get().writes(64))
    }

    fn register_validator() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn slash_validator() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn init_authority_set() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(0))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn rotate_authority_set() -> Weight {
        // 換屆需先以當前集合驗證最終性(走訪所有 precommit 並驗 ed25519 簽章)。
        // Rotation verifies finality under the current set (iterates and verifies
        // every precommit signature) before adopting the next set.
        Weight::from_parts(120_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn register_issuer_vk() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn verify_foreign_proof() -> Weight {
        // Groth16 pairing 驗證為主成本。/ Dominated by the Groth16 pairing check.
        Weight::from_parts(150_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn register_treaty() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(0))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn recognize_foreign_invoice() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn oss_register() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn oss_report() -> Weight {
        Weight::from_parts(18_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(2))
    }
}

// 測試用：以零權重實作，避免基準測試依賴。
//
// For tests: a zero-weight implementation avoiding benchmarking deps.
impl WeightInfo for () {
    fn register_issuer() -> Weight {
        Weight::zero()
    }
    fn submit_instruction() -> Weight {
        Weight::zero()
    }
    fn verify_finality() -> Weight {
        Weight::zero()
    }
    fn net_and_settle() -> Weight {
        Weight::zero()
    }
    fn register_validator() -> Weight {
        Weight::zero()
    }
    fn slash_validator() -> Weight {
        Weight::zero()
    }
    fn init_authority_set() -> Weight {
        Weight::zero()
    }
    fn rotate_authority_set() -> Weight {
        Weight::zero()
    }
    fn register_issuer_vk() -> Weight {
        Weight::zero()
    }
    fn verify_foreign_proof() -> Weight {
        Weight::zero()
    }
    fn register_treaty() -> Weight {
        Weight::zero()
    }
    fn recognize_foreign_invoice() -> Weight {
        Weight::zero()
    }
    fn oss_register() -> Weight {
        Weight::zero()
    }
    fn oss_report() -> Weight {
        Weight::zero()
    }
}
