//! 權重定義 / Autogenerated-style weight definitions for `pallet-federation`.
//!
//! 目前為佔位數值；正式權重應由 `frame-benchmarking` 產生並取代本檔。
//!
//! Placeholder weights. Production weights should be generated via
//! `frame-benchmarking` and substituted here (see `benchmarking.rs`).
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// 本 pallet 交易所需的權重資訊介面。
///
/// Weight functions needed for `pallet_federation`.
pub trait WeightInfo {
    fn propose() -> Weight;
    fn vote() -> Weight;
    fn close() -> Weight;
    fn set_membership() -> Weight;
    fn set_basket() -> Weight;
    fn mint_xsu() -> Weight;
    fn redeem_xsu() -> Weight;
    fn book_clearing() -> Weight;
    fn net_and_settle() -> Weight;
    fn publish_proof_of_reserve() -> Weight;
}

/// 以實機基準測試產生的權重（佔位）。
///
/// Weights for `pallet_federation` using the Substrate node and recommended
/// hardware (placeholder values).
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn propose() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn vote() -> Weight {
        Weight::from_parts(18_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn close() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn set_membership() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(0))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn set_basket() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn mint_xsu() -> Weight {
        Weight::from_parts(22_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn redeem_xsu() -> Weight {
        Weight::from_parts(22_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn book_clearing() -> Weight {
        Weight::from_parts(18_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn net_and_settle() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(0))
            .saturating_add(T::DbWeight::get().writes(0))
    }

    fn publish_proof_of_reserve() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

// 測試用：以零權重實作，避免基準測試依賴。
//
// For tests: a zero-weight implementation avoiding benchmarking deps.
impl WeightInfo for () {
    fn propose() -> Weight {
        Weight::zero()
    }
    fn vote() -> Weight {
        Weight::zero()
    }
    fn close() -> Weight {
        Weight::zero()
    }
    fn set_membership() -> Weight {
        Weight::zero()
    }
    fn set_basket() -> Weight {
        Weight::zero()
    }
    fn mint_xsu() -> Weight {
        Weight::zero()
    }
    fn redeem_xsu() -> Weight {
        Weight::zero()
    }
    fn book_clearing() -> Weight {
        Weight::zero()
    }
    fn net_and_settle() -> Weight {
        Weight::zero()
    }
    fn publish_proof_of_reserve() -> Weight {
        Weight::zero()
    }
}
