//! Autogenerated weights stub for pallet-identity-fer.
//! pallet-identity-fer 的權重資訊（佔位實作，待 benchmarking 產生實際數值）。

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// 權重資訊介面 / Weight functions needed for pallet_identity_fer.
pub trait WeightInfo {
    fn anchor_did() -> Weight;
    fn rotate_keys() -> Weight;
    fn update_revocation() -> Weight;
    fn register_issuer() -> Weight;
}

/// 以 RocksDB 為基準之預設權重實作（佔位值）。
/// Weights for pallet_identity_fer using the Substrate node and `RocksDbWeight`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn anchor_did() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn rotate_keys() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn update_revocation() -> Weight {
        Weight::from_parts(12_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(0))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn register_issuer() -> Weight {
        Weight::from_parts(12_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(0))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

// 供測試使用的單元權重（無 DB 計量）。
/// For backwards compatibility and tests.
impl WeightInfo for () {
    fn anchor_did() -> Weight {
        Weight::from_parts(30_000_000, 0)
    }
    fn rotate_keys() -> Weight {
        Weight::from_parts(20_000_000, 0)
    }
    fn update_revocation() -> Weight {
        Weight::from_parts(12_000_000, 0)
    }
    fn register_issuer() -> Weight {
        Weight::from_parts(12_000_000, 0)
    }
}
