//! 權重定義 / Autogenerated-style weight definitions for `pallet-treasury-fer`.
//!
//! 目前為佔位數值；正式權重應由 `frame-benchmarking` 產生並取代本檔。
//!
//! Placeholder weights. Production weights should be generated via
//! `frame-benchmarking` and substituted here (see `benchmarking.rs`).
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// 本 pallet 交易所需的權重資訊介面。
///
/// Weight functions needed for `pallet_treasury_fer`.
pub trait WeightInfo {
    fn mint() -> Weight;
    fn burn() -> Weight;
    fn subsidize() -> Weight;
    fn record_settlement() -> Weight;
}

/// 以實機基準測試產生的權重（佔位）。
///
/// Weights for `pallet_treasury_fer` using the Substrate node and
/// recommended hardware (placeholder values).
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn mint() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn burn() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn subsidize() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn record_settlement() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

// 測試用：以零權重實作，避免基準測試依賴。
//
// For tests: a zero-weight implementation avoiding benchmarking deps.
impl WeightInfo for () {
    fn mint() -> Weight {
        Weight::zero()
    }
    fn burn() -> Weight {
        Weight::zero()
    }
    fn subsidize() -> Weight {
        Weight::zero()
    }
    fn record_settlement() -> Weight {
        Weight::zero()
    }
}
