//! 權重定義 / Autogenerated-style weight definitions for `pallet-tax`.
//!
//! 目前為佔位數值；正式權重應由 `frame-benchmarking` 產生並取代本檔。
//!
//! Placeholder weights. Production weights should be generated via
//! `frame-benchmarking` and substituted here (see `benchmarking.rs`).
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// 本 pallet 交易所需的權重資訊介面。
///
/// Weight functions needed for `pallet_tax`.
pub trait WeightInfo {
    fn anchor_invoice() -> Weight;
    fn withhold() -> Weight;
    fn file_obligation() -> Weight;
    fn prove_bracket() -> Weight;
    fn settle() -> Weight;
    fn authorize_audit() -> Weight;
    fn set_brackets() -> Weight;
}

/// 以實機基準測試產生的權重（佔位）。
///
/// Weights for `pallet_tax` using the Substrate node and recommended
/// hardware (placeholder values).
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn anchor_invoice() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn withhold() -> Weight {
        Weight::from_parts(10_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(0))
            .saturating_add(T::DbWeight::get().writes(0))
    }

    fn file_obligation() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn prove_bracket() -> Weight {
        Weight::from_parts(50_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(0))
            .saturating_add(T::DbWeight::get().writes(0))
    }

    fn settle() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn authorize_audit() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn set_brackets() -> Weight {
        Weight::from_parts(10_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(0))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

// 測試用：以零權重實作，避免基準測試依賴。
//
// For tests: a zero-weight implementation avoiding benchmarking deps.
impl WeightInfo for () {
    fn anchor_invoice() -> Weight {
        Weight::zero()
    }
    fn withhold() -> Weight {
        Weight::zero()
    }
    fn file_obligation() -> Weight {
        Weight::zero()
    }
    fn prove_bracket() -> Weight {
        Weight::zero()
    }
    fn settle() -> Weight {
        Weight::zero()
    }
    fn authorize_audit() -> Weight {
        Weight::zero()
    }
    fn set_brackets() -> Weight {
        Weight::zero()
    }
}
