//! Autogenerated weights stub for pallet-credential.
//! pallet-credential 的權重資訊（佔位實作，待 benchmarking 產生實際數值）。

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// 權重資訊介面 / Weight functions needed for pallet_credential.
pub trait WeightInfo {
    fn issue() -> Weight;
    fn revoke() -> Weight;
    fn set_status() -> Weight;
    fn log_presentation() -> Weight;
}

/// 以 RocksDB 為基準之預設權重實作（佔位值）。
/// Weights for pallet_credential using the Substrate node and `RocksDbWeight`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn issue() -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn revoke() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn set_status() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn log_presentation() -> Weight {
        Weight::from_parts(12_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

// 供測試使用的單元權重（無 DB 計量）。
/// For backwards compatibility and tests.
impl WeightInfo for () {
    fn issue() -> Weight {
        Weight::from_parts(25_000_000, 0)
    }
    fn revoke() -> Weight {
        Weight::from_parts(15_000_000, 0)
    }
    fn set_status() -> Weight {
        Weight::from_parts(15_000_000, 0)
    }
    fn log_presentation() -> Weight {
        Weight::from_parts(12_000_000, 0)
    }
}
